### ISSUE TITLE
Build failure 

### ISSUE THREAD

**Issue by JonasCir** [plum-umd/bibifi-code#31]
Hi,
I tried to built this project, but compilation runs out of memory with the following error:

```
bibifi                           > [ 70 of 116] Compiling Forms.Survey
bibifi                           > ghc: internal error: Unable to commit 1048576 bytes of memory
bibifi                           >     (GHC version 8.6.5 for x86_64_unknown_linux)
bibifi                           >     Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
Completed 227 action(s).

--  While building package bibifi-0.0.0 using:
      /root/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1 build lib:bibifi exe:bibifi --ghc-options ""
    Process exited with code: ExitFailure (-6)
```

I could reproduce this issue locally using Arch Linux (12 GB RAM + 12 GB SWAP) and on a Ubuntu server (256 GB RAM), both on the host and inside a Docker container.

Compilation runs normal until  "[70 of 116] Compiling Forms.Survey". After this, the compilation does not make any progress and the process continues to consume all available memory.

Does the build works for you?
Any ideas how to work around this?

Best,
Jonas

Might be related:
https://gitlab.haskell.org/ghc/ghc/issues/16613
https://gitlab.haskell.org/ghc/ghc/issues/15500
https://stackoverflow.com/questions/48361850/third-times-the-charm-nondeterministic-stack-ghc
https://gitlab.haskell.org/ghc/ghc/issues/15054

**Comment by jprider63** [comment]
Hi @JonasCir. This is due to a [GHC](https://gitlab.haskell.org/ghc/ghc/issues/13253) [bug](https://gitlab.haskell.org/ghc/ghc/issues/17610). You should be able to build without optimizations with `stack build --fast`.

**Comment by JonasCir** [comment]
Thank you! This worked :smiley:
