### ISSUE TITLE
Grader error: "Could not parse input. Invalid encoding"

### ISSUE THREAD

**Issue by YoshikiTakashima** [plum-umd/bibifi-code#33]
Hi.

I'm Yoshi, a TA at CMU using a fork of your program.

We're hitting an error where the grader complains 
```
{"error":"Could not parse input. Invalid encoding","result":false}
```
even though the input is up to spec with the oracle JSON in https://github.com/plum-umd/bibifi-code/blob/master/docs/API.md. It would be great if you can help us understand what it means by "Invalid encoding."

Furthermore, we only have the binary of that file, so it would also be nice if you can point us to the source.

Thank you!

~Yoshi

**Comment by YoshikiTakashima** [comment]
Example of the input file that is failing (contents of `/tmp/inputjson`)

```
{
  "input":[
    "logappend -T 1 -K secret -A -E Fred log1",
    "logappend -T 2 -K secret -A -G Jill log1",
    "logappend -T 3 -K secret -A -E Fred -R 1 log1",
    "logappend -T 4 -K secret -A -G Jill -R 1 log1",
    "logread -K secret -S log1"
  ],
  "type":"oracle"
}
```

**Comment by ngsankha** [comment]
Hi @YoshikiTakashima, it seems like your input specifications do not match the gallery problem. Can you try this input and us know if this works:

```
{
  "input":[
    {"input": "logappend -T 1 -K secret -A -E Fred log1"},
    {"input": "logappend -T 2 -K secret -A -G Jill log1"},
    {"input": "logappend -T 3 -K secret -A -E Fred -R 1 log1"},
    {"input": "logappend -T 4 -K secret -A -G Jill -R 1 log1"},
    {"input": "logread -K secret -S log1"}
  ],
  "type":"oracle"
}
```

**Comment by YoshikiTakashima** [comment]
Hi @ngsankha.

Thanks for the quick reply.

Your JSON also gets the same reply: `{"error":"Could not parse input. Invalid encoding","result":false}`

**Comment by YoshikiTakashima** [comment]
FYI, the binary I have is this one (it's zipped).
[grader.gz](https://github.com/plum-umd/bibifi-code/files/6016928/grader.gz)

It should run on Intel x86 Linux

**Comment by ngsankha** [comment]
I see where the problem was. The binary you were using is for the Bank problem, the inputs were for the Art Gallery problem, hence the parse error. I have added you to a team on Github that should grant you access to the our private problems repository and the docker image that has instructions on how to build the problem grader/oracles.

The problem repository has more sample input output tests, the complete specifications and source for the grader binaries. Let me know if this helps!

**Comment by YoshikiTakashima** [comment]
Thank you for letting us know. We never really figured out since we only have the binary.

~~So I'm looking at https://github.com/plum-umd/bibifi-problems. While there is a grader under `atm`, isn't that the grader for the bank problem? I don't see any counterpart in the gallery problem (`gallery414`, I assume).~~

~~Also, in bibifi-image/contests, there is `atm` and `ehr`, but neither of them seem to be the gallery problem~~

~~May be I missed something, so if you could point me to the right folder, that would be great.~~

**Comment by YoshikiTakashima** [comment]
After some digging around, it seems like the grading for the Art Gallery is different, and it does not have to be symmetric with the other problem.

Thank you for the help!
